### PR TITLE
Replace Feedback Tab with the Web Widget

### PR DESCRIPTION
**Pull request by mmolina**
:snake:

Replace the Feedback Tab with the Web Widget on Magento Extension.

This is the feature branch in which I was merging all the changes.

New PRs may be merged as we are going to test now the integration with provisioning that was done by Sadia+Likun. Just opeining this PR so we can start reviewing it from Manila.

/cc @zendesk/taipan @miogalang @joseconsador @jwswj

### CODE REVIEW

**Comment by miogalang** [comment]
:+1:

**Comment by joseconsador** [comment]
:+1:

**Comment by jwswj** [comment]
Let's do this! (after #67)

**Comment by mmolina** [comment]
We are going to tag+bundle this, and as soon as Likun is done deploying provisioning we'll push this to Magento Connect.

**Pull request merged**
