### PR TITLE
[CE-707] Data upgrade script from 1.4.0 to 2.0.0

### PR DESCRIPTION
**Pull request by mmolina**
:snake:

Create a data upgrade script to remove the Feedback Tab settings and create the Web Widget ones.

The Web Widget will be _on_ by default, but won't appear on the users' stores unless they set it up on Zendesk.

/cc @zendesk/taipan
### References
- Jira link: https://zendesk.atlassian.net/browse/CE-707
### Risks
- None

### CODE REVIEW

**Comment by liulikun** [comment]
@jwswj I looked at magento maketplace, it looks like the current version for this extension is still '1.3.0', so we haven't publish any new versions since then. If we want to bump the version to '2.0.0', we should be able to skip the upgrade file 1.3.1 and 1.4.0? Just one upgrade file 1.3.0-2.0.0 to squash all the commits in between should be good enough?

**Comment by mmolina** [comment]
Alternatively, we could publish 1.4.0 with master as it is now, containing the recent bug fixes and still using the Feedback Tab so we leave for the records (can be installed using Magento Connect) a 1.x stable version with all those bugs fixed. Once we are finished with the Web Widget integration we can release 2.0.0 to replace the Feedback Tab with the Web Widget.
Some users have installed 1.3.1 and 1.4.0 pulling this repo, so we still need to create data upgrade scripts for them.

**Comment by sadia-zzz** [comment]
:+1:

**Comment by liulikun** [comment]
:+1:

**Comment by jwswj** [comment]
We will be publishing 1.4.0. It's currently being heavily tested.

**Comment by jwswj** [comment]
:+1:

**Comment by mmolina** [comment]
Thanks for letting us know about the status of 1.4.0 @jwswj . Please ping us once it's released to Magento Connect so we can test all the different upgrade paths.

**Pull request merged**
