### PR TITLE
Allow syncing multiple times

### PR DESCRIPTION
**Pull request by joseconsador**
Under Zendesk > Configuration, the "Sync All Customers And Create User Fields" button is usually only clicked once to create the user fields on Zendesk. In the case where this button is pressed more than once, an error will be displayed, which may cause confusion for some users.

screen shot 2015-09-15 at 2 07 10 pm

This PR resolves this by comparing existing user fields to the one's created by this function.

/cc @miogalang @jwswj @mmolina @iandjx 
### References
- Jira link: 
### Risks
- Medium: user fields added by other applications may have their values overwritten

### CODE REVIEW

**Comment by miogalang** [comment]
:+1: Great finally fixing this. Something @mfado would definitely like to see

**Comment by mfado** [comment]
we should probably update the documentation to reflect this, thanks @miogalang + @joseconsador

**Comment by joseconsador** [comment]
Fixes #91

**Comment by jwswj** [comment]
:+1:

**Pull request merged**
